/* eslint-disable prettier/prettier */

import {IProduct} from '../utilities/interfaces/product';

export const listProduct: IProduct[] = [
    {
        id: '1',
        uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
        name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
        price: 875000,
        oldPrice: 920000,
        percentDiscount: 10,
        origin: 'Việt Nam',
        star: 5,
        sold: 32,
    },
    {
        id: '2',
        uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
        name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
        price: 875000,
        oldPrice: 920000,
        percentDiscount: 10,
        origin: 'Anh',
        star: 4,
        sold: 500,
    },
    {
        id: '3',
        uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
        name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
        price: 875000,
        oldPrice: 920000,
        percentDiscount: 10,
        origin: 'Mỹ',
        star: 3,
        sold: 300,
    },
    {
        id: '4',
        uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
        name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
        price: 875000,
        oldPrice: 920000,
        percentDiscount: 10,
        origin: 'Pháp',
        star: 5,
        sold: 120,
    },
    {
        id: '5',
        uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
        name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
        price: 875000,
        oldPrice: 920000,
        percentDiscount: 10,
        origin: 'Tây Ban Nha',
        star: 4,
        sold: 40,
    },
    {
        id: '6',
        uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
        name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
        price: 875000,
        oldPrice: 920000,
        percentDiscount: 10,
        origin: 'Tây Ban Nha',
        star: 4,
        sold: 40,
    },
];

export const productsCart = [
    {
        id: '1',
        store: 'YouMed Store',
        data: [
            {
                id: '1',
                uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
                name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
                price: 875000,
                oldPrice: 920000,
                percentDiscount: 10,
                origin: 'Việt Nam',
                star: 5,
                sold: 32,
            },
            {
                id: '2',
                uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
                name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
                price: 875000,
                oldPrice: 920000,
                percentDiscount: 10,
                origin: 'Anh',
                star: 4,
                sold: 500,
            },
        ],
    },
    {
        id: '2',
        store: 'Bwell Official Store',
        data: [
            {
                id: '3',
                uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
                name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
                price: 875000,
                oldPrice: 920000,
                percentDiscount: 10,
                origin: 'Việt Nam',
                star: 5,
                sold: 32,
            },
            {
                id: '4',
                uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
                name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
                price: 875000,
                oldPrice: 920000,
                percentDiscount: 10,
                origin: 'Anh',
                star: 4,
                sold: 500,
            },
            {
                id: '5',
                uri: 'https://kemembe.com/wp-content/themes/yootheme/cache/69/18-1-691508c5.png',
                name: 'Viên uống dưỡng trắng, làm căng bóng da Wacos Cerepron hộp 60 viên',
                price: 875000,
                oldPrice: 920000,
                percentDiscount: 10,
                origin: 'Anh',
                star: 4,
                sold: 500,
            },
        ],
    },
];
